- name: Set up NodeSource (6.x)
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

- name: Install Node.js package
  apt: pkg=nodejs update_cache=yes

- name: Install Gulp via npm
  npm: name=gulp global=yes

# echo "\nConfiguring NPM..."
# mkdir ~/npm-global
# npm config set prefix '~/npm-global'
# echo "export PATH=~/npm-global/bin:$PATH" >> ~/.profile
# source ~/.profile
